site_name: Shaarli Documentation
repo_url: https://github.com/shaarli/Shaarli
edit_uri: edit/master/doc/md
site_description: The personal, minimalist, super-fast, database free, bookmarking service
theme:
  name: readthedocs
  custom_dir: doc/custom_theme/
docs_dir: doc/md
site_dir: doc/html
# Disable strict mode until ReadTheDocs provides up-to-date MkDocs settings:
# - https://github.com/shaarli/Shaarli/issues/1179
# - https://github.com/rtfd/readthedocs.org/issues/4314
# strict: true

pages:
- Home: index.md
- Setup:
    - Download and Installation: Download-and-Installation.md
    - Upgrade and migration: Upgrade-and-migration.md
    - Server configuration: Server-configuration.md
    - Server security: Server-security.md
    - Shaarli configuration: Shaarli-configuration.md
    - Plugins: Plugins.md
- Docker:
    - Docker 101: docker/docker-101.md
    - Shaarli images: docker/shaarli-images.md
    - Reverse proxy configuration: docker/reverse-proxy-configuration.md
    - Docker resources: docker/resources.md
- Usage:
    - Browsing and searching: Browsing-and-searching.md
    - Sharing content: Sharing-content.md
    - RSS feeds: RSS-feeds.md
    - REST API: REST-API.md
    - Community & Related software: Community-&-Related-software.md
- Guides:
    - Install Shaarli on Debian 9 with Docker: guides/install-shaarli-with-debian9-and-docker.md
    - Backup, restore, import and export: guides/backup-restore-import-export.md
    - Various hacks: guides/various-hacks.md
- Development:
    - Development guidelines: Development-guidelines.md
    - Continuous integration tools: Continuous-integration-tools.md
    - GnuPG signature: GnuPG-signature.md
    - Directory structure: Directory-structure.md
    - Link Structure: Link-structure.md
    - 3rd party libraries: 3rd-party-libraries.md
    - Plugin System: Plugin-System.md
    - Release Shaarli: Release-Shaarli.md
    - Versioning and Branches: Versioning-and-Branches.md
    - Security: Security.md
    - Static analysis: Static-analysis.md
    - Translations: Translations.md
    - Theming: Theming.md
    - Unit tests: Unit-tests.md
    - Unit tests inside Docker: Unit-tests-Docker.md
- FAQ: FAQ.md
- Troubleshooting: Troubleshooting.md
